
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  #What does this do?
  selector:
    matchLabels:
      app: hello
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        #What is this good for?
        track: stable
    spec:
      containers:
      - name: myapi
        image: "myapi"
        #Dont attempt to pull image from remote container registry
        #Use this if image is provided locally
        imagePullPolicy: Never


